/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *fixed1;
  GtkWidget *entry_userame;
  GtkWidget *entry_password;
  GtkWidget *label_hidden_6;
  GtkWidget *login;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label91;
  GtkWidget *creecompte;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label92;
  GtkWidget *label90;
  GtkWidget *label_password_6;
  GtkWidget *label_username_6;
  GtkWidget *label89;
  GtkWidget *image25;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_login, 800, 500);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Login"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER_ALWAYS);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_login), fixed1);

  entry_userame = gtk_entry_new ();
  gtk_widget_show (entry_userame);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_userame, 360, 160);
  gtk_widget_set_size_request (entry_userame, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_userame), 8226);

  entry_password = gtk_entry_new ();
  gtk_widget_show (entry_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_password, 360, 232);
  gtk_widget_set_size_request (entry_password, 160, 30);
  gtk_entry_set_visibility (GTK_ENTRY (entry_password), FALSE);

  label_hidden_6 = gtk_cell_view_new ();
  gtk_widget_show (label_hidden_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_hidden_6, 160, 368);
  gtk_widget_set_size_request (label_hidden_6, 176, 32);

  login = gtk_button_new ();
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed1), login, 240, 312);
  gtk_widget_set_size_request (login, 150, 30);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (login), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Se Connecter"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox23), label91, FALSE, FALSE, 0);

  creecompte = gtk_button_new ();
  gtk_widget_show (creecompte);
  gtk_fixed_put (GTK_FIXED (fixed1), creecompte, 416, 312);
  gtk_widget_set_size_request (creecompte, 150, 30);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (creecompte), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Cr\303\251er un Compte"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox24), label92, FALSE, FALSE, 0);

  label90 = gtk_label_new (_("<span  foreground='#ff6600'  size='large' weight='bold'  style='oblique'>BORDJ LELLA</span>"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed1), label90, 296, 48);
  gtk_widget_set_size_request (label90, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label90), TRUE);
  gtk_label_set_justify (GTK_LABEL (label90), GTK_JUSTIFY_CENTER);

  label_password_6 = gtk_label_new (_("Password :"));
  gtk_widget_show (label_password_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_password_6, 216, 232);
  gtk_widget_set_size_request (label_password_6, 100, 30);

  label_username_6 = gtk_label_new (_("Username :"));
  gtk_widget_show (label_username_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_username_6, 216, 160);
  gtk_widget_set_size_request (label_username_6, 100, 30);

  label89 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed1), label89, 16, 8);
  gtk_widget_set_size_request (label89, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);

  image25 = create_pixmap (window_login, "Sans titre..jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed1), image25, 0, 0);
  gtk_widget_set_size_request (image25, 800, 500);
  gtk_widget_set_sensitive (image25, FALSE);

  g_signal_connect ((gpointer) login, "clicked",
                    G_CALLBACK (on_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) creecompte, "clicked",
                    G_CALLBACK (on_creecompte_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_login, entry_userame, "entry_userame");
  GLADE_HOOKUP_OBJECT (window_login, entry_password, "entry_password");
  GLADE_HOOKUP_OBJECT (window_login, label_hidden_6, "label_hidden_6");
  GLADE_HOOKUP_OBJECT (window_login, login, "login");
  GLADE_HOOKUP_OBJECT (window_login, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window_login, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window_login, image23, "image23");
  GLADE_HOOKUP_OBJECT (window_login, label91, "label91");
  GLADE_HOOKUP_OBJECT (window_login, creecompte, "creecompte");
  GLADE_HOOKUP_OBJECT (window_login, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window_login, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window_login, image24, "image24");
  GLADE_HOOKUP_OBJECT (window_login, label92, "label92");
  GLADE_HOOKUP_OBJECT (window_login, label90, "label90");
  GLADE_HOOKUP_OBJECT (window_login, label_password_6, "label_password_6");
  GLADE_HOOKUP_OBJECT (window_login, label_username_6, "label_username_6");
  GLADE_HOOKUP_OBJECT (window_login, label89, "label89");
  GLADE_HOOKUP_OBJECT (window_login, image25, "image25");

  return window_login;
}

GtkWidget*
create_windowAddClient (void)
{
  GtkWidget *windowAddClient;
  GtkWidget *fixed2;
  GtkWidget *entry_first_name_6;
  GtkWidget *entry_last_name_6;
  GtkWidget *entry_email_6;
  GtkWidget *entry_adress_6;
  GtkWidget *entry_phone_number_6;
  GtkWidget *entry_city_6;
  GtkObject *spinbutton_day_6_adj;
  GtkWidget *spinbutton_day_6;
  GtkObject *spinbutton_mouth_6_adj;
  GtkWidget *spinbutton_mouth_6;
  GtkObject *spinbutton_year_6_adj;
  GtkWidget *spinbutton_year_6;
  GtkWidget *entryid;
  GtkWidget *button_add_client_confirm_6;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label15;
  GtkWidget *button_add_client_back_6;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label88;
  GtkWidget *eventbox1;
  GtkWidget *dateNclieAdd;
  GtkWidget *eventbox2;
  GtkWidget *laleladress;
  GtkWidget *eventbox3;
  GtkWidget *lalelnum;
  GtkWidget *eventbox4;
  GtkWidget *lalelville;
  GtkWidget *eventbox5;
  GtkWidget *resultaddCl;
  GtkWidget *eventbox6;
  GtkWidget *label_adress_6;
  GtkWidget *eventbox7;
  GtkWidget *label_Last_name_6;
  GtkWidget *eventbox8;
  GtkWidget *label_first_name_6;
  GtkWidget *eventbox9;
  GtkWidget *label_mounth;
  GtkWidget *eventbox10;
  GtkWidget *label_year_6;
  GtkWidget *eventbox11;
  GtkWidget *label_birth_date_6;
  GtkWidget *eventbox12;
  GtkWidget *label_phone_number_6;
  GtkWidget *eventbox13;
  GtkWidget *label_day;
  GtkWidget *eventbox14;
  GtkWidget *label86;
  GtkWidget *eventbox15;
  GtkWidget *label85;
  GtkWidget *eventbox16;
  GtkWidget *label_city_6;
  GtkWidget *eventbox17;
  GtkWidget *label87;
  GtkWidget *eventbox18;
  GtkWidget *label_email_6;
  GtkWidget *eventbox19;
  GtkWidget *lalelemail;
  GtkWidget *eventbox20;
  GtkWidget *lalelnom;
  GtkWidget *eventbox21;
  GtkWidget *lalelprenom;
  GtkWidget *eventbox22;
  GtkWidget *idclientVerif;
  GtkWidget *image27;

  windowAddClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAddClient, 790, 520);
  gtk_window_set_title (GTK_WINDOW (windowAddClient), _("Ajouter Client"));
  gtk_window_set_position (GTK_WINDOW (windowAddClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAddClient), fixed2);

  entry_first_name_6 = gtk_entry_new ();
  gtk_widget_show (entry_first_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_first_name_6, 208, 168);
  gtk_widget_set_size_request (entry_first_name_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_first_name_6), 8226);

  entry_last_name_6 = gtk_entry_new ();
  gtk_widget_show (entry_last_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_last_name_6, 560, 170);
  gtk_widget_set_size_request (entry_last_name_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_last_name_6), 8226);

  entry_email_6 = gtk_entry_new ();
  gtk_widget_show (entry_email_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_email_6, 200, 280);
  gtk_widget_set_size_request (entry_email_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_6), 8226);

  entry_adress_6 = gtk_entry_new ();
  gtk_widget_show (entry_adress_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_adress_6, 560, 280);
  gtk_widget_set_size_request (entry_adress_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adress_6), 8226);

  entry_phone_number_6 = gtk_entry_new ();
  gtk_widget_show (entry_phone_number_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_phone_number_6, 200, 350);
  gtk_widget_set_size_request (entry_phone_number_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_phone_number_6), 8226);

  entry_city_6 = gtk_entry_new ();
  gtk_widget_show (entry_city_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_city_6, 560, 352);
  gtk_widget_set_size_request (entry_city_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_city_6), 8226);

  spinbutton_day_6_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_day_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_day_6_adj), 1, 0);
  gtk_widget_show (spinbutton_day_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_day_6, 380, 232);
  gtk_widget_set_size_request (spinbutton_day_6, 60, 25);

  spinbutton_mouth_6_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mouth_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mouth_6_adj), 1, 0);
  gtk_widget_show (spinbutton_mouth_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mouth_6, 500, 232);
  gtk_widget_set_size_request (spinbutton_mouth_6, 60, 25);

  spinbutton_year_6_adj = gtk_adjustment_new (2020, 1950, 2030, 1, 10, 10);
  spinbutton_year_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_year_6_adj), 1, 0);
  gtk_widget_show (spinbutton_year_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_year_6, 636, 232);
  gtk_widget_set_size_request (spinbutton_year_6, 60, 25);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed2), entryid, 376, 121);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  button_add_client_confirm_6 = gtk_button_new ();
  gtk_widget_show (button_add_client_confirm_6);
  gtk_fixed_put (GTK_FIXED (fixed2), button_add_client_confirm_6, 364, 416);
  gtk_widget_set_size_request (button_add_client_confirm_6, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_add_client_confirm_6), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox2), label15, FALSE, FALSE, 0);

  button_add_client_back_6 = gtk_button_new ();
  gtk_widget_show (button_add_client_back_6);
  gtk_fixed_put (GTK_FIXED (fixed2), button_add_client_back_6, 32, 480);
  gtk_widget_set_size_request (button_add_client_back_6, 100, 30);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button_add_client_back_6), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox22), label88, FALSE, FALSE, 0);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox1, 712, 232);
  gtk_widget_set_size_request (eventbox1, 30, 27);

  dateNclieAdd = gtk_label_new ("");
  gtk_widget_show (dateNclieAdd);
  gtk_container_add (GTK_CONTAINER (eventbox1), dateNclieAdd);
  gtk_widget_set_size_request (dateNclieAdd, 30, 27);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox2, 720, 280);
  gtk_widget_set_size_request (eventbox2, 30, 27);

  laleladress = gtk_label_new ("");
  gtk_widget_show (laleladress);
  gtk_container_add (GTK_CONTAINER (eventbox2), laleladress);
  gtk_widget_set_size_request (laleladress, 30, 27);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox3, 368, 350);
  gtk_widget_set_size_request (eventbox3, 30, 27);

  lalelnum = gtk_label_new ("");
  gtk_widget_show (lalelnum);
  gtk_container_add (GTK_CONTAINER (eventbox3), lalelnum);
  gtk_widget_set_size_request (lalelnum, 30, 27);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox4, 720, 352);
  gtk_widget_set_size_request (eventbox4, 32, 27);

  lalelville = gtk_label_new ("");
  gtk_widget_show (lalelville);
  gtk_container_add (GTK_CONTAINER (eventbox4), lalelville);
  gtk_widget_set_size_request (lalelville, 32, 27);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox5, 176, 456);
  gtk_widget_set_size_request (eventbox5, 500, 30);

  resultaddCl = gtk_label_new (_("**********"));
  gtk_widget_show (resultaddCl);
  gtk_container_add (GTK_CONTAINER (eventbox5), resultaddCl);
  gtk_widget_set_size_request (resultaddCl, 500, 30);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox6, 474, 280);
  gtk_widget_set_size_request (eventbox6, 70, 27);

  label_adress_6 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label_adress_6);
  gtk_container_add (GTK_CONTAINER (eventbox6), label_adress_6);
  gtk_widget_set_size_request (label_adress_6, 70, 27);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox7, 466, 170);
  gtk_widget_set_size_request (eventbox7, 80, 27);

  label_Last_name_6 = gtk_label_new (_("Pr\303\251nom  :"));
  gtk_widget_show (label_Last_name_6);
  gtk_container_add (GTK_CONTAINER (eventbox7), label_Last_name_6);
  gtk_widget_set_size_request (label_Last_name_6, 80, 27);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox8, 136, 170);
  gtk_widget_set_size_request (eventbox8, 60, 27);

  label_first_name_6 = gtk_label_new (_("Nom  :"));
  gtk_widget_show (label_first_name_6);
  gtk_container_add (GTK_CONTAINER (eventbox8), label_first_name_6);
  gtk_widget_set_size_request (label_first_name_6, 60, 27);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox9, 444, 230);
  gtk_widget_set_size_request (eventbox9, 55, 30);

  label_mounth = gtk_label_new (_("Mois :"));
  gtk_widget_show (label_mounth);
  gtk_container_add (GTK_CONTAINER (eventbox9), label_mounth);
  gtk_widget_set_size_request (label_mounth, 55, 30);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox10, 572, 230);
  gtk_widget_set_size_request (eventbox10, 60, 30);

  label_year_6 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label_year_6);
  gtk_container_add (GTK_CONTAINER (eventbox10), label_year_6);
  gtk_widget_set_size_request (label_year_6, 60, 30);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox11, 176, 230);
  gtk_widget_set_size_request (eventbox11, 150, 27);

  label_birth_date_6 = gtk_label_new (_("Date de naissance  :"));
  gtk_widget_show (label_birth_date_6);
  gtk_container_add (GTK_CONTAINER (eventbox11), label_birth_date_6);
  gtk_widget_set_size_request (label_birth_date_6, 150, 27);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox12, 48, 352);
  gtk_widget_set_size_request (eventbox12, 150, 27);

  label_phone_number_6 = gtk_label_new (_("Num\303\251ro t\303\251l\303\251phone :"));
  gtk_widget_show (label_phone_number_6);
  gtk_container_add (GTK_CONTAINER (eventbox12), label_phone_number_6);
  gtk_widget_set_size_request (label_phone_number_6, 150, 27);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox13, 316, 230);
  gtk_widget_set_size_request (eventbox13, 60, 30);

  label_day = gtk_label_new (_("Jour :"));
  gtk_widget_show (label_day);
  gtk_container_add (GTK_CONTAINER (eventbox13), label_day);
  gtk_widget_set_size_request (label_day, 60, 30);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox14, 318, 40);
  gtk_widget_set_size_request (eventbox14, 248, 56);

  label86 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Ajouter Client</span>"));
  gtk_widget_show (label86);
  gtk_container_add (GTK_CONTAINER (eventbox14), label86);
  gtk_widget_set_size_request (label86, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label86), TRUE);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox15, 16, 8);
  gtk_widget_set_size_request (eventbox15, 160, 46);

  label85 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label85);
  gtk_container_add (GTK_CONTAINER (eventbox15), label85);
  gtk_widget_set_size_request (label85, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label85), TRUE);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox16, 488, 350);
  gtk_widget_set_size_request (eventbox16, 60, 27);

  label_city_6 = gtk_label_new (_("Ville  :"));
  gtk_widget_show (label_city_6);
  gtk_container_add (GTK_CONTAINER (eventbox16), label_city_6);
  gtk_widget_set_size_request (label_city_6, 60, 27);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox17, 328, 120);
  gtk_widget_set_size_request (eventbox17, 50, 27);

  label87 = gtk_label_new (_("ID :"));
  gtk_widget_show (label87);
  gtk_container_add (GTK_CONTAINER (eventbox17), label87);
  gtk_widget_set_size_request (label87, 50, 27);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox18, 135, 280);
  gtk_widget_set_size_request (eventbox18, 60, 27);

  label_email_6 = gtk_label_new (_("Email :"));
  gtk_widget_show (label_email_6);
  gtk_container_add (GTK_CONTAINER (eventbox18), label_email_6);
  gtk_widget_set_size_request (label_email_6, 60, 27);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox19, 368, 280);
  gtk_widget_set_size_request (eventbox19, 30, 27);

  lalelemail = gtk_label_new ("");
  gtk_widget_show (lalelemail);
  gtk_container_add (GTK_CONTAINER (eventbox19), lalelemail);
  gtk_widget_set_size_request (lalelemail, 30, 27);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox20, 376, 168);
  gtk_widget_set_size_request (eventbox20, 30, 27);

  lalelnom = gtk_label_new ("");
  gtk_widget_show (lalelnom);
  gtk_container_add (GTK_CONTAINER (eventbox20), lalelnom);
  gtk_widget_set_size_request (lalelnom, 30, 27);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox21, 728, 168);
  gtk_widget_set_size_request (eventbox21, 30, 27);

  lalelprenom = gtk_label_new ("");
  gtk_widget_show (lalelprenom);
  gtk_container_add (GTK_CONTAINER (eventbox21), lalelprenom);
  gtk_widget_set_size_request (lalelprenom, 30, 27);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 537, 120);
  gtk_widget_set_size_request (eventbox22, 29, 27);

  idclientVerif = gtk_label_new ("");
  gtk_widget_show (idclientVerif);
  gtk_container_add (GTK_CONTAINER (eventbox22), idclientVerif);
  gtk_widget_set_size_request (idclientVerif, 29, 27);

  image27 = create_pixmap (windowAddClient, "Sans titre..jpg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed2), image27, 0, 0);
  gtk_widget_set_size_request (image27, 792, 520);

  g_signal_connect ((gpointer) button_add_client_confirm_6, "clicked",
                    G_CALLBACK (on_button_add_client_confirm_6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_add_client_back_6, "clicked",
                    G_CALLBACK (on_button_add_client_back_6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAddClient, windowAddClient, "windowAddClient");
  GLADE_HOOKUP_OBJECT (windowAddClient, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_first_name_6, "entry_first_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_last_name_6, "entry_last_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_email_6, "entry_email_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_adress_6, "entry_adress_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_phone_number_6, "entry_phone_number_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_city_6, "entry_city_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_day_6, "spinbutton_day_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_mouth_6, "spinbutton_mouth_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_year_6, "spinbutton_year_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (windowAddClient, button_add_client_confirm_6, "button_add_client_confirm_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowAddClient, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowAddClient, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowAddClient, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowAddClient, button_add_client_back_6, "button_add_client_back_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (windowAddClient, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (windowAddClient, image22, "image22");
  GLADE_HOOKUP_OBJECT (windowAddClient, label88, "label88");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (windowAddClient, dateNclieAdd, "dateNclieAdd");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (windowAddClient, laleladress, "laleladress");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelnum, "lalelnum");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelville, "lalelville");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (windowAddClient, resultaddCl, "resultaddCl");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_adress_6, "label_adress_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_Last_name_6, "label_Last_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_first_name_6, "label_first_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_mounth, "label_mounth");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_year_6, "label_year_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_birth_date_6, "label_birth_date_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_phone_number_6, "label_phone_number_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_day, "label_day");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (windowAddClient, label86, "label86");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (windowAddClient, label85, "label85");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_city_6, "label_city_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (windowAddClient, label87, "label87");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_email_6, "label_email_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelemail, "lalelemail");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelnom, "lalelnom");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelprenom, "lalelprenom");
  GLADE_HOOKUP_OBJECT (windowAddClient, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (windowAddClient, idclientVerif, "idclientVerif");
  GLADE_HOOKUP_OBJECT (windowAddClient, image27, "image27");

  return windowAddClient;
}

GtkWidget*
create_windowEditClient (void)
{
  GtkWidget *windowEditClient;
  GtkWidget *fixed3;
  GtkWidget *entry_new_email;
  GtkWidget *entry_new_adress;
  GtkWidget *entry_new_city;
  GtkWidget *entry_new_number;
  GtkWidget *idclientEdit;
  GtkWidget *fisrtnameClEdit;
  GtkWidget *lastnameClEdit;
  GtkWidget *consultclient;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label64;
  GtkWidget *button_back_edit_profile;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label84;
  GtkWidget *button_confirm_edit_profile;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label28;
  GtkWidget *image28;
  GtkWidget *eventbox23;
  GtkWidget *Adress;
  GtkWidget *eventbox24;
  GtkWidget *label80;
  GtkWidget *eventbox25;
  GtkWidget *label81;
  GtkWidget *eventbox26;
  GtkWidget *label63;
  GtkWidget *eventbox27;
  GtkWidget *label83;
  GtkWidget *eventbox28;
  GtkWidget *City_;
  GtkWidget *eventbox29;
  GtkWidget *resultEditCl;
  GtkWidget *eventbox30;
  GtkWidget *Phonenumber;
  GtkWidget *eventbox31;
  GtkWidget *ee;
  GtkWidget *eventbox32;
  GtkWidget *aa;
  GtkWidget *eventbox33;
  GtkWidget *lalelEMAIL;
  GtkWidget *eventbox34;
  GtkWidget *lalelNOM;
  GtkWidget *eventbox35;
  GtkWidget *lalelPRENOMM;
  GtkWidget *eventbox36;
  GtkWidget *lalelADRESS;
  GtkWidget *eventbox37;
  GtkWidget *lalelVILLE;
  GtkWidget *eventbox38;
  GtkWidget *lalelNUM;

  windowEditClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowEditClient, 800, 500);
  gtk_window_set_title (GTK_WINDOW (windowEditClient), _("Modifier Client"));
  gtk_window_set_position (GTK_WINDOW (windowEditClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowEditClient), fixed3);

  entry_new_email = gtk_entry_new ();
  gtk_widget_show (entry_new_email);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_email, 168, 262);
  gtk_widget_set_size_request (entry_new_email, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_email), 8226);

  entry_new_adress = gtk_entry_new ();
  gtk_widget_show (entry_new_adress);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_adress, 520, 332);
  gtk_widget_set_size_request (entry_new_adress, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_adress), 8226);

  entry_new_city = gtk_entry_new ();
  gtk_widget_show (entry_new_city);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_city, 520, 262);
  gtk_widget_set_size_request (entry_new_city, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_city), 8226);

  entry_new_number = gtk_entry_new ();
  gtk_widget_show (entry_new_number);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_number, 168, 332);
  gtk_widget_set_size_request (entry_new_number, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_number), 8226);

  idclientEdit = gtk_entry_new ();
  gtk_widget_show (idclientEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), idclientEdit, 312, 120);
  gtk_widget_set_size_request (idclientEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idclientEdit), 8226);

  fisrtnameClEdit = gtk_entry_new ();
  gtk_widget_show (fisrtnameClEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), fisrtnameClEdit, 168, 192);
  gtk_widget_set_size_request (fisrtnameClEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (fisrtnameClEdit), 8226);

  lastnameClEdit = gtk_entry_new ();
  gtk_widget_show (lastnameClEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), lastnameClEdit, 520, 192);
  gtk_widget_set_size_request (lastnameClEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (lastnameClEdit), 8226);

  consultclient = gtk_button_new ();
  gtk_widget_show (consultclient);
  gtk_fixed_put (GTK_FIXED (fixed3), consultclient, 504, 120);
  gtk_widget_set_size_request (consultclient, 100, 27);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (consultclient), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox15), label64, FALSE, FALSE, 0);

  button_back_edit_profile = gtk_button_new ();
  gtk_widget_show (button_back_edit_profile);
  gtk_fixed_put (GTK_FIXED (fixed3), button_back_edit_profile, 24, 456);
  gtk_widget_set_size_request (button_back_edit_profile, 100, 30);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_back_edit_profile), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox21), label84, FALSE, FALSE, 0);

  button_confirm_edit_profile = gtk_button_new ();
  gtk_widget_show (button_confirm_edit_profile);
  gtk_fixed_put (GTK_FIXED (fixed3), button_confirm_edit_profile, 368, 400);
  gtk_widget_set_size_request (button_confirm_edit_profile, 100, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_confirm_edit_profile), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox4), label28, FALSE, FALSE, 0);

  image28 = create_pixmap (windowEditClient, "Sans titre..jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed3), image28, 0, 0);
  gtk_widget_set_size_request (image28, 808, 504);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox23, 435, 332);
  gtk_widget_set_size_request (eventbox23, 65, 30);

  Adress = gtk_label_new (_("Adresse :"));
  gtk_widget_show (Adress);
  gtk_container_add (GTK_CONTAINER (eventbox23), Adress);
  gtk_widget_set_size_request (Adress, 65, 30);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox24, 16, 8);
  gtk_widget_set_size_request (eventbox24, 160, 46);

  label80 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label80);
  gtk_container_add (GTK_CONTAINER (eventbox24), label80);
  gtk_widget_set_size_request (label80, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label80), TRUE);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox25, 304, 40);
  gtk_widget_set_size_request (eventbox25, 248, 56);

  label81 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Modifier Client</span>"));
  gtk_widget_show (label81);
  gtk_container_add (GTK_CONTAINER (eventbox25), label81);
  gtk_widget_set_size_request (label81, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label81), TRUE);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox26, 256, 120);
  gtk_widget_set_size_request (eventbox26, 49, 27);

  label63 = gtk_label_new (_("ID :"));
  gtk_widget_show (label63);
  gtk_container_add (GTK_CONTAINER (eventbox26), label63);
  gtk_widget_set_size_request (label63, 49, 27);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox27, 424, 192);
  gtk_widget_set_size_request (eventbox27, 80, 27);

  label83 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label83);
  gtk_container_add (GTK_CONTAINER (eventbox27), label83);
  gtk_widget_set_size_request (label83, 80, 27);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox28, 448, 262);
  gtk_widget_set_size_request (eventbox28, 60, 27);

  City_ = gtk_label_new (_("Ville:"));
  gtk_widget_show (City_);
  gtk_container_add (GTK_CONTAINER (eventbox28), City_);
  gtk_widget_set_size_request (City_, 60, 27);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox29, 168, 440);
  gtk_widget_set_size_request (eventbox29, 500, 30);

  resultEditCl = gtk_label_new (_("**********"));
  gtk_widget_show (resultEditCl);
  gtk_container_add (GTK_CONTAINER (eventbox29), resultEditCl);
  gtk_widget_set_size_request (resultEditCl, 500, 30);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox30, 8, 332);
  gtk_widget_set_size_request (eventbox30, 150, 27);

  Phonenumber = gtk_label_new (_("Num\303\251ro t\303\251l\303\251phone :"));
  gtk_widget_show (Phonenumber);
  gtk_container_add (GTK_CONTAINER (eventbox30), Phonenumber);
  gtk_widget_set_size_request (Phonenumber, 150, 27);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox31, 96, 262);
  gtk_widget_set_size_request (eventbox31, 60, 27);

  ee = gtk_label_new (_("Email :"));
  gtk_widget_show (ee);
  gtk_container_add (GTK_CONTAINER (eventbox31), ee);
  gtk_widget_set_size_request (ee, 60, 27);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox32, 96, 192);
  gtk_widget_set_size_request (eventbox32, 60, 27);

  aa = gtk_label_new (_("Nom :"));
  gtk_widget_show (aa);
  gtk_container_add (GTK_CONTAINER (eventbox32), aa);
  gtk_widget_set_size_request (aa, 60, 27);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox33, 336, 264);
  gtk_widget_set_size_request (eventbox33, 30, 27);

  lalelEMAIL = gtk_label_new ("");
  gtk_widget_show (lalelEMAIL);
  gtk_container_add (GTK_CONTAINER (eventbox33), lalelEMAIL);
  gtk_widget_set_size_request (lalelEMAIL, 30, 27);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox34, 336, 192);
  gtk_widget_set_size_request (eventbox34, 30, 27);

  lalelNOM = gtk_label_new ("");
  gtk_widget_show (lalelNOM);
  gtk_container_add (GTK_CONTAINER (eventbox34), lalelNOM);
  gtk_widget_set_size_request (lalelNOM, 30, 27);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox35, 688, 192);
  gtk_widget_set_size_request (eventbox35, 30, 27);

  lalelPRENOMM = gtk_label_new ("");
  gtk_widget_show (lalelPRENOMM);
  gtk_container_add (GTK_CONTAINER (eventbox35), lalelPRENOMM);
  gtk_widget_set_size_request (lalelPRENOMM, 30, 27);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox36, 688, 336);
  gtk_widget_set_size_request (eventbox36, 30, 27);

  lalelADRESS = gtk_label_new ("");
  gtk_widget_show (lalelADRESS);
  gtk_container_add (GTK_CONTAINER (eventbox36), lalelADRESS);
  gtk_widget_set_size_request (lalelADRESS, 30, 27);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox37, 688, 264);
  gtk_widget_set_size_request (eventbox37, 30, 27);

  lalelVILLE = gtk_label_new ("");
  gtk_widget_show (lalelVILLE);
  gtk_container_add (GTK_CONTAINER (eventbox37), lalelVILLE);
  gtk_widget_set_size_request (lalelVILLE, 30, 27);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox38, 336, 336);
  gtk_widget_set_size_request (eventbox38, 30, 27);

  lalelNUM = gtk_label_new ("");
  gtk_widget_show (lalelNUM);
  gtk_container_add (GTK_CONTAINER (eventbox38), lalelNUM);
  gtk_widget_set_size_request (lalelNUM, 30, 27);

  g_signal_connect ((gpointer) consultclient, "clicked",
                    G_CALLBACK (on_consultclient_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_back_edit_profile, "clicked",
                    G_CALLBACK (on_button_back_edit_profile_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_confirm_edit_profile, "clicked",
                    G_CALLBACK (on_button_confirm_edit_profile_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowEditClient, windowEditClient, "windowEditClient");
  GLADE_HOOKUP_OBJECT (windowEditClient, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_email, "entry_new_email");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_adress, "entry_new_adress");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_city, "entry_new_city");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_number, "entry_new_number");
  GLADE_HOOKUP_OBJECT (windowEditClient, idclientEdit, "idclientEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, fisrtnameClEdit, "fisrtnameClEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, lastnameClEdit, "lastnameClEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, consultclient, "consultclient");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowEditClient, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowEditClient, label64, "label64");
  GLADE_HOOKUP_OBJECT (windowEditClient, button_back_edit_profile, "button_back_edit_profile");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (windowEditClient, image21, "image21");
  GLADE_HOOKUP_OBJECT (windowEditClient, label84, "label84");
  GLADE_HOOKUP_OBJECT (windowEditClient, button_confirm_edit_profile, "button_confirm_edit_profile");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowEditClient, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowEditClient, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowEditClient, image28, "image28");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (windowEditClient, Adress, "Adress");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (windowEditClient, label80, "label80");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (windowEditClient, label81, "label81");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (windowEditClient, label63, "label63");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (windowEditClient, label83, "label83");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (windowEditClient, City_, "City_");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (windowEditClient, resultEditCl, "resultEditCl");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (windowEditClient, Phonenumber, "Phonenumber");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (windowEditClient, ee, "ee");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (windowEditClient, aa, "aa");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelEMAIL, "lalelEMAIL");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelNOM, "lalelNOM");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelPRENOMM, "lalelPRENOMM");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelADRESS, "lalelADRESS");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelVILLE, "lalelVILLE");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelNUM, "lalelNUM");

  return windowEditClient;
}

GtkWidget*
create_windowGesClient (void)
{
  GtkWidget *windowGesClient;
  GtkWidget *fixed4;
  GtkWidget *label76;
  GtkWidget *addClient;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label79;
  GtkWidget *gotomodifier;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label59;
  GtkWidget *gotodelete;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label58;
  GtkWidget *homeGesClien;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label60;
  GtkWidget *buttonrefresh;
  GtkWidget *image26;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_admin_clients;
  GtkWidget *label77;
  GtkWidget *label94;
  GtkWidget *image29;

  windowGesClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGesClient, 970, 570);
  gtk_window_set_title (GTK_WINDOW (windowGesClient), _("Gestion des clients"));
  gtk_window_set_position (GTK_WINDOW (windowGesClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowGesClient), fixed4);
  gtk_widget_set_size_request (fixed4, 1000, 500);

  label76 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed4), label76, 16, 8);
  gtk_widget_set_size_request (label76, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label76), TRUE);

  addClient = gtk_button_new ();
  gtk_widget_show (addClient);
  gtk_fixed_put (GTK_FIXED (fixed4), addClient, 32, 144);
  gtk_widget_set_size_request (addClient, 100, 50);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (addClient), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox20), label79, FALSE, FALSE, 0);

  gotomodifier = gtk_button_new ();
  gtk_widget_show (gotomodifier);
  gtk_fixed_put (GTK_FIXED (fixed4), gotomodifier, 32, 214);
  gtk_widget_set_size_request (gotomodifier, 100, 50);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (gotomodifier), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox11), label59, FALSE, FALSE, 0);

  gotodelete = gtk_button_new ();
  gtk_widget_show (gotodelete);
  gtk_fixed_put (GTK_FIXED (fixed4), gotodelete, 32, 284);
  gtk_widget_set_size_request (gotodelete, 100, 50);
  gtk_button_set_relief (GTK_BUTTON (gotodelete), GTK_RELIEF_HALF);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (gotodelete), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox10), label58, FALSE, FALSE, 0);

  homeGesClien = gtk_button_new ();
  gtk_widget_show (homeGesClien);
  gtk_fixed_put (GTK_FIXED (fixed4), homeGesClien, 824, 64);
  gtk_widget_set_size_request (homeGesClien, 100, 50);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (homeGesClien), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox12), label60, FALSE, FALSE, 0);

  buttonrefresh = gtk_button_new ();
  gtk_widget_show (buttonrefresh);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonrefresh, 490, 488);
  gtk_widget_set_size_request (buttonrefresh, 30, 30);

  image26 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_container_add (GTK_CONTAINER (buttonrefresh), image26);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 152, 128);
  gtk_widget_set_size_request (scrolledwindow1, 670, 352);

  treeview_admin_clients = gtk_tree_view_new ();
  gtk_widget_show (treeview_admin_clients);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_admin_clients);
  gtk_widget_set_size_request (treeview_admin_clients, 632, 312);

  label77 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Gestion des clients</span>"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed4), label77, 392, 32);
  gtk_widget_set_size_request (label77, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label77), TRUE);

  label94 = gtk_label_new (_("<span  foreground='#ff0000'  size='large' weight='bold'  style='roman'> *Double clique sur client  pour supprimer \n                  puis cliquer sur actualiser</span>"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed4), label94, 280, 520);
  gtk_widget_set_size_request (label94, 441, 48);
  gtk_label_set_use_markup (GTK_LABEL (label94), TRUE);

  image29 = create_pixmap (windowGesClient, "Sans titre..jpg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed4), image29, 0, 0);
  gtk_widget_set_size_request (image29, 976, 576);
  gtk_widget_set_sensitive (image29, FALSE);

  g_signal_connect ((gpointer) addClient, "clicked",
                    G_CALLBACK (on_addClient_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotomodifier, "clicked",
                    G_CALLBACK (on_gotomodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotodelete, "clicked",
                    G_CALLBACK (on_gotodelete_clicked),
                    NULL);
  g_signal_connect ((gpointer) homeGesClien, "clicked",
                    G_CALLBACK (on_buttonacceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrefresh, "clicked",
                    G_CALLBACK (on_buttonrefresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_admin_clients, "row_activated",
                    G_CALLBACK (on_treeview_admin_clients_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGesClient, windowGesClient, "windowGesClient");
  GLADE_HOOKUP_OBJECT (windowGesClient, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowGesClient, label76, "label76");
  GLADE_HOOKUP_OBJECT (windowGesClient, addClient, "addClient");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowGesClient, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowGesClient, label79, "label79");
  GLADE_HOOKUP_OBJECT (windowGesClient, gotomodifier, "gotomodifier");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowGesClient, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowGesClient, label59, "label59");
  GLADE_HOOKUP_OBJECT (windowGesClient, gotodelete, "gotodelete");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowGesClient, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowGesClient, label58, "label58");
  GLADE_HOOKUP_OBJECT (windowGesClient, homeGesClien, "homeGesClien");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowGesClient, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowGesClient, label60, "label60");
  GLADE_HOOKUP_OBJECT (windowGesClient, buttonrefresh, "buttonrefresh");
  GLADE_HOOKUP_OBJECT (windowGesClient, image26, "image26");
  GLADE_HOOKUP_OBJECT (windowGesClient, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowGesClient, treeview_admin_clients, "treeview_admin_clients");
  GLADE_HOOKUP_OBJECT (windowGesClient, label77, "label77");
  GLADE_HOOKUP_OBJECT (windowGesClient, label94, "label94");
  GLADE_HOOKUP_OBJECT (windowGesClient, image29, "image29");

  return windowGesClient;
}

GtkWidget*
create_windowDelClient (void)
{
  GtkWidget *windowDelClient;
  GtkWidget *fixed6;
  GtkWidget *entrysuppid;
  GtkWidget *labelsupprimerid;
  GtkWidget *buttonretourdelete;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label75;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *button_clients_delete;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label55;
  GtkWidget *outputDelClient;
  GtkWidget *image30;

  windowDelClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowDelClient, 700, 450);
  gtk_window_set_title (GTK_WINDOW (windowDelClient), _("delete"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowDelClient), fixed6);
  gtk_widget_set_size_request (fixed6, 528, 440);

  entrysuppid = gtk_entry_new ();
  gtk_widget_show (entrysuppid);
  gtk_fixed_put (GTK_FIXED (fixed6), entrysuppid, 256, 184);
  gtk_widget_set_size_request (entrysuppid, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysuppid), 8226);

  labelsupprimerid = gtk_label_new (_("ID :"));
  gtk_widget_show (labelsupprimerid);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsupprimerid, 184, 184);
  gtk_widget_set_size_request (labelsupprimerid, 49, 30);

  buttonretourdelete = gtk_button_new ();
  gtk_widget_show (buttonretourdelete);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonretourdelete, 24, 376);
  gtk_widget_set_size_request (buttonretourdelete, 100, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonretourdelete), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox18), label75, FALSE, FALSE, 0);

  label72 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed6), label72, 16, 8);
  gtk_widget_set_size_request (label72, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  label73 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Supprimer Client</span>"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed6), label73, 280, 56);
  gtk_widget_set_size_request (label73, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label73), TRUE);

  button_clients_delete = gtk_button_new ();
  gtk_widget_show (button_clients_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), button_clients_delete, 440, 184);
  gtk_widget_set_size_request (button_clients_delete, 128, 30);
  gtk_container_set_border_width (GTK_CONTAINER (button_clients_delete), 1);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_clients_delete), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image8), 1, 1);
  gtk_misc_set_padding (GTK_MISC (image8), 1, 1);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox8), label55, FALSE, FALSE, 0);

  outputDelClient = gtk_label_new (_("***************"));
  gtk_widget_show (outputDelClient);
  gtk_fixed_put (GTK_FIXED (fixed6), outputDelClient, 200, 280);
  gtk_widget_set_size_request (outputDelClient, 400, 30);

  image30 = create_pixmap (windowDelClient, "Sans titre..jpg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed6), image30, 0, 0);
  gtk_widget_set_size_request (image30, 704, 456);
  gtk_widget_set_sensitive (image30, FALSE);

  g_signal_connect ((gpointer) buttonretourdelete, "clicked",
                    G_CALLBACK (on_buttonretourdelete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_clients_delete, "clicked",
                    G_CALLBACK (on_button_clients_delete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowDelClient, windowDelClient, "windowDelClient");
  GLADE_HOOKUP_OBJECT (windowDelClient, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowDelClient, entrysuppid, "entrysuppid");
  GLADE_HOOKUP_OBJECT (windowDelClient, labelsupprimerid, "labelsupprimerid");
  GLADE_HOOKUP_OBJECT (windowDelClient, buttonretourdelete, "buttonretourdelete");
  GLADE_HOOKUP_OBJECT (windowDelClient, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowDelClient, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowDelClient, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowDelClient, label75, "label75");
  GLADE_HOOKUP_OBJECT (windowDelClient, label72, "label72");
  GLADE_HOOKUP_OBJECT (windowDelClient, label73, "label73");
  GLADE_HOOKUP_OBJECT (windowDelClient, button_clients_delete, "button_clients_delete");
  GLADE_HOOKUP_OBJECT (windowDelClient, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowDelClient, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowDelClient, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowDelClient, label55, "label55");
  GLADE_HOOKUP_OBJECT (windowDelClient, outputDelClient, "outputDelClient");
  GLADE_HOOKUP_OBJECT (windowDelClient, image30, "image30");

  return windowDelClient;
}

GtkWidget*
create_windowEditPass (void)
{
  GtkWidget *windowEditPass;
  GtkWidget *fixed7;
  GtkWidget *label66;
  GtkWidget *label65;
  GtkWidget *appliquerchangement;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label70;
  GtkWidget *retourGesClient;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label71;
  GtkWidget *oldpass;
  GtkWidget *label67;
  GtkWidget *newpass1;
  GtkWidget *label68;
  GtkWidget *newpass2;
  GtkWidget *label69;
  GtkWidget *image31;

  windowEditPass = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowEditPass, 790, 500);
  gtk_window_set_title (GTK_WINDOW (windowEditPass), _("Changer mot de passe"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (windowEditPass), fixed7);
  gtk_widget_set_size_request (fixed7, 616, 400);

  label66 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Changer mot de passe</span>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed7), label66, 328, 56);
  gtk_widget_set_size_request (label66, 200, 30);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  label65 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed7), label65, 16, 8);
  gtk_widget_set_size_request (label65, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  appliquerchangement = gtk_button_new ();
  gtk_widget_show (appliquerchangement);
  gtk_fixed_put (GTK_FIXED (fixed7), appliquerchangement, 432, 360);
  gtk_widget_set_size_request (appliquerchangement, 100, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (appliquerchangement), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox16), label70, FALSE, FALSE, 0);

  retourGesClient = gtk_button_new ();
  gtk_widget_show (retourGesClient);
  gtk_fixed_put (GTK_FIXED (fixed7), retourGesClient, 312, 360);
  gtk_widget_set_size_request (retourGesClient, 100, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (retourGesClient), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox17), label71, FALSE, FALSE, 0);

  oldpass = gtk_entry_new ();
  gtk_widget_show (oldpass);
  gtk_fixed_put (GTK_FIXED (fixed7), oldpass, 416, 152);
  gtk_widget_set_size_request (oldpass, 200, 30);
  gtk_entry_set_visibility (GTK_ENTRY (oldpass), FALSE);

  label67 = gtk_label_new (_("Ancien mot de passe :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed7), label67, 180, 152);
  gtk_widget_set_size_request (label67, 200, 30);

  newpass1 = gtk_entry_new ();
  gtk_widget_show (newpass1);
  gtk_fixed_put (GTK_FIXED (fixed7), newpass1, 416, 222);
  gtk_widget_set_size_request (newpass1, 200, 30);
  gtk_entry_set_visibility (GTK_ENTRY (newpass1), FALSE);

  label68 = gtk_label_new (_("Nouveau mot de pass :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed7), label68, 180, 222);
  gtk_widget_set_size_request (label68, 200, 30);

  newpass2 = gtk_entry_new ();
  gtk_widget_show (newpass2);
  gtk_fixed_put (GTK_FIXED (fixed7), newpass2, 416, 292);
  gtk_widget_set_size_request (newpass2, 200, 30);
  gtk_entry_set_visibility (GTK_ENTRY (newpass2), FALSE);

  label69 = gtk_label_new (_("Nouveau mot de pass :"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed7), label69, 180, 292);
  gtk_widget_set_size_request (label69, 200, 30);

  image31 = create_pixmap (windowEditPass, "Sans titre..jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed7), image31, 0, 0);
  gtk_widget_set_size_request (image31, 792, 512);
  gtk_widget_set_sensitive (image31, FALSE);

  g_signal_connect ((gpointer) appliquerchangement, "clicked",
                    G_CALLBACK (on_appliquerchangement_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourGesClient, "clicked",
                    G_CALLBACK (on_retourGesClient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowEditPass, windowEditPass, "windowEditPass");
  GLADE_HOOKUP_OBJECT (windowEditPass, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowEditPass, label66, "label66");
  GLADE_HOOKUP_OBJECT (windowEditPass, label65, "label65");
  GLADE_HOOKUP_OBJECT (windowEditPass, appliquerchangement, "appliquerchangement");
  GLADE_HOOKUP_OBJECT (windowEditPass, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (windowEditPass, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowEditPass, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowEditPass, label70, "label70");
  GLADE_HOOKUP_OBJECT (windowEditPass, retourGesClient, "retourGesClient");
  GLADE_HOOKUP_OBJECT (windowEditPass, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (windowEditPass, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (windowEditPass, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowEditPass, label71, "label71");
  GLADE_HOOKUP_OBJECT (windowEditPass, oldpass, "oldpass");
  GLADE_HOOKUP_OBJECT (windowEditPass, label67, "label67");
  GLADE_HOOKUP_OBJECT (windowEditPass, newpass1, "newpass1");
  GLADE_HOOKUP_OBJECT (windowEditPass, label68, "label68");
  GLADE_HOOKUP_OBJECT (windowEditPass, newpass2, "newpass2");
  GLADE_HOOKUP_OBJECT (windowEditPass, label69, "label69");
  GLADE_HOOKUP_OBJECT (windowEditPass, image31, "image31");

  return windowEditPass;
}

GtkWidget*
create_windowAnSech (void)
{
  GtkWidget *windowAnSech;
  GtkWidget *fixed8;
  GtkWidget *TbuttonAfficheAnSech;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image32;
  GtkWidget *label95;
  GtkWidget *labelAnSech;
  GtkWidget *textviewAnseche;

  windowAnSech = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAnSech, 700, 450);
  gtk_window_set_title (GTK_WINDOW (windowAnSech), _("ann\303\251e la plus s\303\251che"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (windowAnSech), fixed8);

  TbuttonAfficheAnSech = gtk_button_new ();
  gtk_widget_show (TbuttonAfficheAnSech);
  gtk_fixed_put (GTK_FIXED (fixed8), TbuttonAfficheAnSech, 240, 336);
  gtk_widget_set_size_request (TbuttonAfficheAnSech, 152, 37);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (TbuttonAfficheAnSech), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image32 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox25), image32, FALSE, FALSE, 0);

  label95 = gtk_label_new (_("<span font_desc=\"black\"foreground=\"green\"> Afficher l'ann\303\251e </span>"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox25), label95, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label95), TRUE);

  labelAnSech = gtk_label_new (_("<span font_desc=\"Purisa\"foreground=\"purple\"> L'ann\303\251e La Plus S\303\251che : </span>"));
  gtk_widget_show (labelAnSech);
  gtk_fixed_put (GTK_FIXED (fixed8), labelAnSech, 88, 216);
  gtk_widget_set_size_request (labelAnSech, 232, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelAnSech), TRUE);

  textviewAnseche = gtk_label_new ("");
  gtk_widget_show (textviewAnseche);
  gtk_fixed_put (GTK_FIXED (fixed8), textviewAnseche, 280, 256);
  gtk_widget_set_size_request (textviewAnseche, 80, 32);

  g_signal_connect ((gpointer) TbuttonAfficheAnSech, "clicked",
                    G_CALLBACK (on_TbuttonAfficheAnSech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAnSech, windowAnSech, "windowAnSech");
  GLADE_HOOKUP_OBJECT (windowAnSech, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowAnSech, TbuttonAfficheAnSech, "TbuttonAfficheAnSech");
  GLADE_HOOKUP_OBJECT (windowAnSech, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (windowAnSech, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (windowAnSech, image32, "image32");
  GLADE_HOOKUP_OBJECT (windowAnSech, label95, "label95");
  GLADE_HOOKUP_OBJECT (windowAnSech, labelAnSech, "labelAnSech");
  GLADE_HOOKUP_OBJECT (windowAnSech, textviewAnseche, "textviewAnseche");

  return windowAnSech;
}

