/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowtroupeaux (void)
{
  GtkWidget *windowtroupeaux;
  GtkWidget *fixed1;
  GtkWidget *entrynom;
  GtkWidget *idsupprimer;
  GtkWidget *calendar1;
  GtkWidget *labelnom;
  GtkWidget *combo1;
  GtkWidget *labelgenretropeau;
  GtkWidget *combotype;
  GtkWidget *labeltype;
  GtkWidget *labelnaissance;
  GtkWidget *label12;
  GtkWidget *label14;
  GtkWidget *type;
  GtkWidget *nom;
  GtkWidget *genre;
  GtkWidget *l1;
  GtkWidget *img5;
  GtkWidget *img15;
  GtkWidget *img3;
  GtkWidget *img1;
  GtkWidget *img4;
  GtkWidget *img2;
  GtkWidget *img6;
  GtkWidget *img16;
  GtkWidget *buttonajoutetroupeaux;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *labelajouter;
  GtkWidget *buttonafficher;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label107;

  windowtroupeaux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowtroupeaux, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (windowtroupeaux), _("Ajouter Un Troupeau :"));
  gtk_window_set_position (GTK_WINDOW (windowtroupeaux), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowtroupeaux), fixed1);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 160, 296);
  gtk_widget_set_size_request (entrynom, 136, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  idsupprimer = gtk_label_new ("");
  gtk_widget_show (idsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), idsupprimer, 472, 760);
  gtk_widget_set_size_request (idsupprimer, 49, 17);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 656, 176);
  gtk_widget_set_size_request (calendar1, 280, 306);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  labelnom = gtk_label_new (_("Nom du troupeau : "));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom, 16, 288);
  gtk_widget_set_size_request (labelnom, 136, 40);

  combo1 = gtk_combo_box_new_text ();
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed1), combo1, 160, 400);
  gtk_widget_set_size_request (combo1, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("./"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("female"));

  labelgenretropeau = gtk_label_new (_("Genre :"));
  gtk_widget_show (labelgenretropeau);
  gtk_fixed_put (GTK_FIXED (fixed1), labelgenretropeau, 0, 400);
  gtk_widget_set_size_request (labelgenretropeau, 88, 32);

  combotype = gtk_combo_box_new_text ();
  gtk_widget_show (combotype);
  gtk_fixed_put (GTK_FIXED (fixed1), combotype, 160, 192);
  gtk_widget_set_size_request (combotype, 137, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("./"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combotype), _("veaux"));

  labeltype = gtk_label_new (_("Type : "));
  gtk_widget_show (labeltype);
  gtk_fixed_put (GTK_FIXED (fixed1), labeltype, 8, 184);
  gtk_widget_set_size_request (labeltype, 80, 41);

  labelnaissance = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelnaissance);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnaissance, 728, 144);
  gtk_widget_set_size_request (labelnaissance, 136, 24);

  label12 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion Des Troupeaux        </span>\n"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 384, 24);
  gtk_widget_set_size_request (label12, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label14 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 8, 40);
  gtk_widget_set_size_request (label14, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  type = gtk_label_new (_("label123"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed1), type, 368, 200);
  gtk_widget_set_size_request (type, 192, 16);
  gtk_label_set_use_markup (GTK_LABEL (type), TRUE);

  nom = gtk_label_new (_("label124"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 376, 304);
  gtk_widget_set_size_request (nom, 184, 17);

  genre = gtk_label_new (_("label125"));
  gtk_widget_show (genre);
  gtk_fixed_put (GTK_FIXED (fixed1), genre, 368, 408);
  gtk_widget_set_size_request (genre, 192, 17);
  gtk_label_set_use_markup (GTK_LABEL (genre), TRUE);

  l1 = gtk_label_new (_("label148"));
  gtk_widget_show (l1);
  gtk_fixed_put (GTK_FIXED (fixed1), l1, 712, 488);
  gtk_widget_set_size_request (l1, 168, 25);

  img5 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img5);
  gtk_fixed_put (GTK_FIXED (fixed1), img5, 304, 408);
  gtk_widget_set_size_request (img5, 40, 25);

  img15 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img15);
  gtk_fixed_put (GTK_FIXED (fixed1), img15, 944, 304);
  gtk_widget_set_size_request (img15, 40, 40);

  img3 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img3);
  gtk_fixed_put (GTK_FIXED (fixed1), img3, 304, 296);
  gtk_widget_set_size_request (img3, 40, 25);

  img1 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img1);
  gtk_fixed_put (GTK_FIXED (fixed1), img1, 304, 192);
  gtk_widget_set_size_request (img1, 32, 25);

  img4 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img4);
  gtk_fixed_put (GTK_FIXED (fixed1), img4, 304, 296);
  gtk_widget_set_size_request (img4, 40, 25);

  img2 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img2);
  gtk_fixed_put (GTK_FIXED (fixed1), img2, 296, 184);
  gtk_widget_set_size_request (img2, 48, 33);

  img6 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img6);
  gtk_fixed_put (GTK_FIXED (fixed1), img6, 312, 400);
  gtk_widget_set_size_request (img6, 32, 33);

  img16 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img16);
  gtk_fixed_put (GTK_FIXED (fixed1), img16, 944, 304);
  gtk_widget_set_size_request (img16, 40, 32);

  buttonajoutetroupeaux = gtk_button_new ();
  gtk_widget_show (buttonajoutetroupeaux);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajoutetroupeaux, 440, 504);
  gtk_widget_set_size_request (buttonajoutetroupeaux, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonajoutetroupeaux), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  labelajouter = gtk_label_new (_("<span foreground='black' weight='bold'>ajouter troupeau en cours...</span>"));
  gtk_widget_show (labelajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), labelajouter, 328, 560);
  gtk_widget_set_size_request (labelajouter, 344, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelajouter), TRUE);

  buttonafficher = gtk_button_new ();
  gtk_widget_show (buttonafficher);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonafficher, 24, 584);
  gtk_widget_set_size_request (buttonafficher, 104, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonafficher), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label107 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox19), label107, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonajoutetroupeaux, "clicked",
                    G_CALLBACK (on_buttonajoutetroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher, "clicked",
                    G_CALLBACK (on_buttonafficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowtroupeaux, windowtroupeaux, "windowtroupeaux");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, idsupprimer, "idsupprimer");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, labelgenretropeau, "labelgenretropeau");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, combotype, "combotype");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, labeltype, "labeltype");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, labelnaissance, "labelnaissance");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, type, "type");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, nom, "nom");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, genre, "genre");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, l1, "l1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img5, "img5");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img15, "img15");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img3, "img3");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img1, "img1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img4, "img4");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img2, "img2");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img6, "img6");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, img16, "img16");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, buttonajoutetroupeaux, "buttonajoutetroupeaux");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, labelajouter, "labelajouter");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, buttonafficher, "buttonafficher");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowtroupeaux, label107, "label107");

  return windowtroupeaux;
}

GtkWidget*
create_affichagetroupeaux (void)
{
  GtkWidget *affichagetroupeaux;
  GtkWidget *fixed2;
  GtkWidget *label147;
  GtkWidget *b;
  GtkWidget *v;
  GtkWidget *label114;
  GtkWidget *label113;
  GtkWidget *buttonajouter;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label108;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label109;
  GtkWidget *suppaff;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label110;
  GtkWidget *buttontype;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label112;
  GtkWidget *quittez;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label123;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *actualiser;
  GtkWidget *image39;
  GtkWidget *label126;

  affichagetroupeaux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (affichagetroupeaux, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (affichagetroupeaux), _("Affichage Des Troupeaux :"));
  gtk_window_set_position (GTK_WINDOW (affichagetroupeaux), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (affichagetroupeaux), fixed2);

  label147 = gtk_label_new (_("<span color='black'>\nChoix d 'affichage : </span>\n"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed2), label147, 848, 120);
  gtk_widget_set_size_request (label147, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label147), TRUE);

  b = gtk_check_button_new_with_mnemonic (_("Brebi"));
  gtk_widget_show (b);
  gtk_fixed_put (GTK_FIXED (fixed2), b, 856, 184);
  gtk_widget_set_size_request (b, 118, 24);

  v = gtk_check_button_new_with_mnemonic (_("Veaux"));
  gtk_widget_show (v);
  gtk_fixed_put (GTK_FIXED (fixed2), v, 856, 232);
  gtk_widget_set_size_request (v, 118, 24);

  label114 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed2), label114, 16, 56);
  gtk_widget_set_size_request (label114, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  label113 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion Des Troupeaux        </span>\n"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed2), label113, 392, 24);
  gtk_widget_set_size_request (label113, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonajouter, 56, 160);
  gtk_widget_set_size_request (buttonajouter, 112, 45);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonajouter), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox20), label108, FALSE, FALSE, 0);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonmodifier, 56, 256);
  gtk_widget_set_size_request (buttonmodifier, 112, 45);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox21), label109, FALSE, FALSE, 0);

  suppaff = gtk_button_new ();
  gtk_widget_show (suppaff);
  gtk_fixed_put (GTK_FIXED (fixed2), suppaff, 56, 344);
  gtk_widget_set_size_request (suppaff, 112, 45);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (suppaff), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox22), label110, FALSE, FALSE, 0);

  buttontype = gtk_button_new ();
  gtk_widget_show (buttontype);
  gtk_fixed_put (GTK_FIXED (fixed2), buttontype, 56, 440);
  gtk_widget_set_size_request (buttontype, 112, 45);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (buttontype), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("Nombre \nde toupeaux "));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox24), label112, FALSE, FALSE, 0);

  quittez = gtk_button_new ();
  gtk_widget_show (quittez);
  gtk_fixed_put (GTK_FIXED (fixed2), quittez, 56, 592);
  gtk_widget_set_size_request (quittez, 112, 45);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (quittez), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label123 = gtk_label_new_with_mnemonic (_("Quittez "));
  gtk_widget_show (label123);
  gtk_box_pack_start (GTK_BOX (hbox28), label123, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 200, 136);
  gtk_widget_set_size_request (scrolledwindow1, 640, 400);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser, 800, 88);
  gtk_widget_set_size_request (actualiser, 32, 37);

  image39 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_container_add (GTK_CONTAINER (actualiser), image39);

  label126 = gtk_label_new (_("<span foreground='red' weight='bold' >*Choisir votre op\303\251ration en double cliquant sur votre cible*</span>"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed2), label126, 288, 552);
  gtk_widget_set_size_request (label126, 488, 17);
  gtk_label_set_use_markup (GTK_LABEL (label126), TRUE);

  g_signal_connect ((gpointer) b, "toggled",
                    G_CALLBACK (on_b_toggled),
                    NULL);
  g_signal_connect ((gpointer) v, "toggled",
                    G_CALLBACK (on_v_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) suppaff, "clicked",
                    G_CALLBACK (on_suppaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttontype, "clicked",
                    G_CALLBACK (on_buttontype_clicked),
                    NULL);
  g_signal_connect ((gpointer) quittez, "clicked",
                    G_CALLBACK (on_quittez_clicked),
                    NULL);
  g_signal_connect_after ((gpointer) treeview1, "row_activated",
                          G_CALLBACK (on_treeview1_row_activated),
                          NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichagetroupeaux, affichagetroupeaux, "affichagetroupeaux");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label147, "label147");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, b, "b");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, v, "v");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label114, "label114");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label113, "label113");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image20, "image20");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label108, "label108");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image21, "image21");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label109, "label109");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, suppaff, "suppaff");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image22, "image22");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label110, "label110");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, buttontype, "buttontype");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image24, "image24");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label112, "label112");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, quittez, "quittez");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image28, "image28");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label123, "label123");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, image39, "image39");
  GLADE_HOOKUP_OBJECT (affichagetroupeaux, label126, "label126");

  return affichagetroupeaux;
}

GtkWidget*
create_windowsuppmod (void)
{
  GtkWidget *windowsuppmod;
  GtkWidget *fixed3;
  GtkWidget *entry3;
  GtkWidget *label116;
  GtkWidget *supp;
  GtkWidget *label115;
  GtkWidget *img11;
  GtkWidget *labelsup;
  GtkWidget *labelsup2;
  GtkWidget *supression;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label67;
  GtkWidget *labelsup1;
  GtkWidget *supretour;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label119;

  windowsuppmod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowsuppmod, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (windowsuppmod), _("Supprimer Un Troupeau :"));
  gtk_window_set_position (GTK_WINDOW (windowsuppmod), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowsuppmod), fixed3);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 488, 248);
  gtk_widget_set_size_request (entry3, 104, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label116 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed3), label116, 72, 64);
  gtk_widget_set_size_request (label116, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  supp = gtk_label_new (_("ID :"));
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed3), supp, 392, 248);
  gtk_widget_set_size_request (supp, 80, 25);

  label115 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion des troupeaux        </span>\n"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed3), label115, 408, 32);
  gtk_widget_set_size_request (label115, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label115), TRUE);

  img11 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img11);
  gtk_fixed_put (GTK_FIXED (fixed3), img11, 608, 248);
  gtk_widget_set_size_request (img11, 32, 25);

  labelsup = gtk_label_new (_("label126"));
  gtk_widget_show (labelsup);
  gtk_fixed_put (GTK_FIXED (fixed3), labelsup, 656, 248);
  gtk_widget_set_size_request (labelsup, 288, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelsup), TRUE);

  labelsup2 = gtk_label_new (_("label126"));
  gtk_widget_show (labelsup2);
  gtk_fixed_put (GTK_FIXED (fixed3), labelsup2, 352, 336);
  gtk_widget_set_size_request (labelsup2, 384, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelsup2), TRUE);

  supression = gtk_button_new ();
  gtk_widget_show (supression);
  gtk_fixed_put (GTK_FIXED (fixed3), supression, 488, 416);
  gtk_widget_set_size_request (supression, 104, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supression), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox8), label67, FALSE, FALSE, 0);

  labelsup1 = gtk_label_new (_("<span foreground='black' weight='bold'>suppression en cours...</span>"));
  gtk_widget_show (labelsup1);
  gtk_fixed_put (GTK_FIXED (fixed3), labelsup1, 400, 496);
  gtk_widget_set_size_request (labelsup1, 264, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelsup1), TRUE);

  supretour = gtk_button_new ();
  gtk_widget_show (supretour);
  gtk_fixed_put (GTK_FIXED (fixed3), supretour, 32, 592);
  gtk_widget_set_size_request (supretour, 104, 32);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (supretour), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox25), label119, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supression, "clicked",
                    G_CALLBACK (on_supression_clicked),
                    NULL);
  g_signal_connect ((gpointer) supretour, "clicked",
                    G_CALLBACK (on_supretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowsuppmod, windowsuppmod, "windowsuppmod");
  GLADE_HOOKUP_OBJECT (windowsuppmod, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowsuppmod, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (windowsuppmod, label116, "label116");
  GLADE_HOOKUP_OBJECT (windowsuppmod, supp, "supp");
  GLADE_HOOKUP_OBJECT (windowsuppmod, label115, "label115");
  GLADE_HOOKUP_OBJECT (windowsuppmod, img11, "img11");
  GLADE_HOOKUP_OBJECT (windowsuppmod, labelsup, "labelsup");
  GLADE_HOOKUP_OBJECT (windowsuppmod, labelsup2, "labelsup2");
  GLADE_HOOKUP_OBJECT (windowsuppmod, supression, "supression");
  GLADE_HOOKUP_OBJECT (windowsuppmod, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowsuppmod, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowsuppmod, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowsuppmod, label67, "label67");
  GLADE_HOOKUP_OBJECT (windowsuppmod, labelsup1, "labelsup1");
  GLADE_HOOKUP_OBJECT (windowsuppmod, supretour, "supretour");
  GLADE_HOOKUP_OBJECT (windowsuppmod, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (windowsuppmod, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (windowsuppmod, image25, "image25");
  GLADE_HOOKUP_OBJECT (windowsuppmod, label119, "label119");

  return windowsuppmod;
}

GtkWidget*
create_idtroupeaumodifier (void)
{
  GtkWidget *idtroupeaumodifier;
  GtkWidget *fixed7;
  GtkWidget *entry4;
  GtkWidget *label118;
  GtkWidget *labelidm;
  GtkWidget *label117;
  GtkWidget *img9;
  GtkWidget *labelmod;
  GtkWidget *img10;
  GtkWidget *modifierid;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label88;
  GtkWidget *labelverif;
  GtkWidget *buttonmodretour;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label120;
  GtkWidget *labelinf;

  idtroupeaumodifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (idtroupeaumodifier, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (idtroupeaumodifier), _("Modifier  Un Troupeau :"));
  gtk_window_set_position (GTK_WINDOW (idtroupeaumodifier), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (idtroupeaumodifier), fixed7);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4, 472, 248);
  gtk_widget_set_size_request (entry4, 104, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label118 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed7), label118, 72, 64);
  gtk_widget_set_size_request (label118, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label118), TRUE);

  labelidm = gtk_label_new (_("ID :"));
  gtk_widget_show (labelidm);
  gtk_fixed_put (GTK_FIXED (fixed7), labelidm, 392, 248);
  gtk_widget_set_size_request (labelidm, 72, 25);

  label117 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion des troupeaux        </span>\n"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed7), label117, 400, 24);
  gtk_widget_set_size_request (label117, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label117), TRUE);

  img9 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img9);
  gtk_fixed_put (GTK_FIXED (fixed7), img9, 584, 240);
  gtk_widget_set_size_request (img9, 40, 33);

  labelmod = gtk_label_new (_("label124"));
  gtk_widget_show (labelmod);
  gtk_fixed_put (GTK_FIXED (fixed7), labelmod, 640, 248);
  gtk_widget_set_size_request (labelmod, 360, 25);

  img10 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img10);
  gtk_fixed_put (GTK_FIXED (fixed7), img10, 592, 232);
  gtk_widget_set_size_request (img10, 32, 41);

  modifierid = gtk_button_new ();
  gtk_widget_show (modifierid);
  gtk_fixed_put (GTK_FIXED (fixed7), modifierid, 472, 424);
  gtk_widget_set_size_request (modifierid, 104, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (modifierid), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox12), label88, FALSE, FALSE, 0);

  labelverif = gtk_label_new (_("<span foreground='black' weight='bold' >modification de troupeau en cours...</span>"));
  gtk_widget_show (labelverif);
  gtk_fixed_put (GTK_FIXED (fixed7), labelverif, 384, 504);
  gtk_widget_set_size_request (labelverif, 280, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelverif), TRUE);

  buttonmodretour = gtk_button_new ();
  gtk_widget_show (buttonmodretour);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonmodretour, 24, 584);
  gtk_widget_set_size_request (buttonmodretour, 104, 37);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (buttonmodretour), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label120 = gtk_label_new_with_mnemonic (_("Retour "));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox26), label120, FALSE, FALSE, 0);

  labelinf = gtk_label_new (_("label126"));
  gtk_widget_show (labelinf);
  gtk_fixed_put (GTK_FIXED (fixed7), labelinf, 128, 328);
  gtk_widget_set_size_request (labelinf, 800, 33);

  g_signal_connect ((gpointer) modifierid, "clicked",
                    G_CALLBACK (on_modifierid_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodretour, "clicked",
                    G_CALLBACK (on_buttonmodretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (idtroupeaumodifier, idtroupeaumodifier, "idtroupeaumodifier");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, label118, "label118");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, labelidm, "labelidm");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, label117, "label117");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, img9, "img9");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, labelmod, "labelmod");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, img10, "img10");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, modifierid, "modifierid");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, image12, "image12");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, label88, "label88");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, labelverif, "labelverif");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, buttonmodretour, "buttonmodretour");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, image26, "image26");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, label120, "label120");
  GLADE_HOOKUP_OBJECT (idtroupeaumodifier, labelinf, "labelinf");

  return idtroupeaumodifier;
}

GtkWidget*
create_modifiertroupeau (void)
{
  GtkWidget *modifiertroupeau;
  GtkWidget *fixed8;
  GtkWidget *entry2;
  GtkWidget *fixed9;
  GtkWidget *calendar2;
  GtkWidget *label121;
  GtkWidget *label89;
  GtkWidget *combobox4;
  GtkWidget *label96;
  GtkWidget *combobox3;
  GtkWidget *labelnomt;
  GtkWidget *label97;
  GtkWidget *l2;
  GtkWidget *label91;
  GtkWidget *label95;
  GtkWidget *img8;
  GtkWidget *img7;
  GtkWidget *img20;
  GtkWidget *img21;
  GtkWidget *enregistrermodifier;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label101;
  GtkWidget *label125;
  GtkWidget *buttonmodifretour;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image40;
  GtkWidget *label148;

  modifiertroupeau = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifiertroupeau, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (modifiertroupeau), _("Modifier Un Troupeau :"));
  gtk_window_set_position (GTK_WINDOW (modifiertroupeau), GTK_WIN_POS_CENTER);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (modifiertroupeau), fixed8);
  gtk_widget_set_size_request (fixed8, 1600, 1200);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed8), entry2, 144, 352);
  gtk_widget_set_size_request (entry2, 136, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed9, 56, 672);
  gtk_widget_set_size_request (fixed9, 0, 0);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed8), calendar2, 656, 224);
  gtk_widget_set_size_request (calendar2, 296, 256);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label121 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed8), label121, 40, 64);
  gtk_widget_set_size_request (label121, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);

  label89 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion des troupeaux        </span>\n"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed8), label89, 392, 16);
  gtk_widget_set_size_request (label89, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox4, 144, 464);
  gtk_widget_set_size_request (combobox4, 137, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("female"));

  label96 = gtk_label_new (_("Genre :"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed8), label96, 16, 464);
  gtk_widget_set_size_request (label96, 72, 32);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox3, 144, 240);
  gtk_widget_set_size_request (combobox3, 137, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("veaux"));

  labelnomt = gtk_label_new (_("label124"));
  gtk_widget_show (labelnomt);
  gtk_fixed_put (GTK_FIXED (fixed8), labelnomt, 328, 352);
  gtk_widget_set_size_request (labelnomt, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelnomt), TRUE);

  label97 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed8), label97, 728, 168);
  gtk_widget_set_size_request (label97, 136, 32);

  l2 = gtk_label_new (_("label148"));
  gtk_widget_show (l2);
  gtk_fixed_put (GTK_FIXED (fixed8), l2, 680, 504);
  gtk_widget_set_size_request (l2, 264, 25);

  label91 = gtk_label_new (_("Type : "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed8), label91, 8, 240);
  gtk_widget_set_size_request (label91, 80, 33);

  label95 = gtk_label_new (_("Nom du troupeau : "));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed8), label95, 16, 352);
  gtk_widget_set_size_request (label95, 128, 24);

  img8 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img8);
  gtk_fixed_put (GTK_FIXED (fixed8), img8, 288, 344);
  gtk_widget_set_size_request (img8, 40, 33);

  img7 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img7);
  gtk_fixed_put (GTK_FIXED (fixed8), img7, 288, 344);
  gtk_widget_set_size_request (img7, 32, 33);

  img20 = gtk_label_new (_("\342\234\224\357\270\217"));
  gtk_widget_show (img20);
  gtk_fixed_put (GTK_FIXED (fixed8), img20, 952, 328);
  gtk_widget_set_size_request (img20, 48, 49);

  img21 = gtk_label_new (_("\342\235\214"));
  gtk_widget_show (img21);
  gtk_fixed_put (GTK_FIXED (fixed8), img21, 960, 336);
  gtk_widget_set_size_request (img21, 32, 33);

  enregistrermodifier = gtk_button_new ();
  gtk_widget_show (enregistrermodifier);
  gtk_fixed_put (GTK_FIXED (fixed8), enregistrermodifier, 440, 536);
  gtk_widget_set_size_request (enregistrermodifier, 128, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (enregistrermodifier), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Enregistrez les\n modification "));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox13), label101, FALSE, FALSE, 0);

  label125 = gtk_label_new (_("<span foreground='black' weight='bold' >modification de troupeau en cours...</span>"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed8), label125, 376, 608);
  gtk_widget_set_size_request (label125, 280, 17);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);

  buttonmodifretour = gtk_button_new ();
  gtk_widget_show (buttonmodifretour);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonmodifretour, 32, 592);
  gtk_widget_set_size_request (buttonmodifretour, 128, 37);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (buttonmodifretour), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image40 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox34), image40, FALSE, FALSE, 0);

  label148 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox34), label148, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) enregistrermodifier, "clicked",
                    G_CALLBACK (on_enregistrermodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifretour, "clicked",
                    G_CALLBACK (on_buttonmodifretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifiertroupeau, modifiertroupeau, "modifiertroupeau");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label121, "label121");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label89, "label89");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label96, "label96");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, labelnomt, "labelnomt");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label97, "label97");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, l2, "l2");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label91, "label91");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label95, "label95");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, img8, "img8");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, img7, "img7");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, img20, "img20");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, img21, "img21");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, enregistrermodifier, "enregistrermodifier");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, image13, "image13");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label101, "label101");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label125, "label125");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, buttonmodifretour, "buttonmodifretour");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, image40, "image40");
  GLADE_HOOKUP_OBJECT (modifiertroupeau, label148, "label148");

  return modifiertroupeau;
}

GtkWidget*
create_typedetroupeaux (void)
{
  GtkWidget *typedetroupeaux;
  GtkWidget *fixed10;
  GtkWidget *label133;
  GtkWidget *label129;
  GtkWidget *label128;
  GtkWidget *totale;
  GSList *totale_group = NULL;
  GtkWidget *brebi;
  GtkWidget *veaux;
  GtkWidget *retaff;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label136;
  GtkWidget *Confirmer;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label135;

  typedetroupeaux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (typedetroupeaux, 1000, 650);
  gtk_window_set_title (GTK_WINDOW (typedetroupeaux), _("Nombe Du Troupeaux Par Type :"));
  gtk_window_set_position (GTK_WINDOW (typedetroupeaux), GTK_WIN_POS_CENTER);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (typedetroupeaux), fixed10);

  label133 = gtk_label_new (_("<span foreground='black' weight='bold' >Le nombre du troupeaux totale ou par type :</span>"));
  gtk_widget_show (label133);
  gtk_fixed_put (GTK_FIXED (fixed10), label133, 360, 168);
  gtk_widget_set_size_request (label133, 328, 41);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  label129 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>\n"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed10), label129, 48, 64);
  gtk_widget_set_size_request (label129, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  label128 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'       >       Gestion Des Troupeaux        </span>\n"));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed10), label128, 392, 32);
  gtk_widget_set_size_request (label128, 240, 49);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);

  totale = gtk_radio_button_new_with_mnemonic (NULL, _("Totale"));
  gtk_widget_show (totale);
  gtk_fixed_put (GTK_FIXED (fixed10), totale, 480, 280);
  gtk_widget_set_size_request (totale, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (totale), totale_group);
  totale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (totale));

  brebi = gtk_radio_button_new_with_mnemonic (NULL, _("Brebi"));
  gtk_widget_show (brebi);
  gtk_fixed_put (GTK_FIXED (fixed10), brebi, 480, 392);
  gtk_widget_set_size_request (brebi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (brebi), totale_group);
  totale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (brebi));

  veaux = gtk_radio_button_new_with_mnemonic (NULL, _("Veaux"));
  gtk_widget_show (veaux);
  gtk_fixed_put (GTK_FIXED (fixed10), veaux, 480, 512);
  gtk_widget_set_size_request (veaux, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (veaux), totale_group);
  totale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (veaux));

  retaff = gtk_button_new ();
  gtk_widget_show (retaff);
  gtk_fixed_put (GTK_FIXED (fixed10), retaff, 24, 584);
  gtk_widget_set_size_request (retaff, 104, 37);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (retaff), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label136 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label136);
  gtk_box_pack_start (GTK_BOX (hbox31), label136, FALSE, FALSE, 0);

  Confirmer = gtk_button_new ();
  gtk_widget_show (Confirmer);
  gtk_fixed_put (GTK_FIXED (fixed10), Confirmer, 464, 560);
  gtk_widget_set_size_request (Confirmer, 104, 37);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (Confirmer), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label135 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (hbox30), label135, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) totale, "toggled",
                    G_CALLBACK (on_totale_toggled),
                    NULL);
  g_signal_connect ((gpointer) brebi, "toggled",
                    G_CALLBACK (on_brebi_toggled),
                    NULL);
  g_signal_connect ((gpointer) veaux, "toggled",
                    G_CALLBACK (on_veaux_toggled),
                    NULL);
  g_signal_connect ((gpointer) retaff, "clicked",
                    G_CALLBACK (on_retaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) Confirmer, "clicked",
                    G_CALLBACK (on_Confirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (typedetroupeaux, typedetroupeaux, "typedetroupeaux");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, label133, "label133");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, label129, "label129");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, label128, "label128");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, totale, "totale");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, brebi, "brebi");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, veaux, "veaux");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, retaff, "retaff");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, image31, "image31");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, label136, "label136");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, Confirmer, "Confirmer");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, image30, "image30");
  GLADE_HOOKUP_OBJECT (typedetroupeaux, label135, "label135");

  return typedetroupeaux;
}

GtkWidget*
create_ajoutoui (void)
{
  GtkWidget *ajoutoui;
  GtkWidget *fixed11;
  GtkWidget *okajout;
  GtkWidget *label137;
  GtkWidget *image32;

  ajoutoui = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (ajoutoui, 400, 300);
  gtk_window_set_title (GTK_WINDOW (ajoutoui), _("Alerte D'Ajout"));
  gtk_window_set_position (GTK_WINDOW (ajoutoui), GTK_WIN_POS_CENTER);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (ajoutoui), fixed11);

  okajout = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (okajout);
  gtk_fixed_put (GTK_FIXED (fixed11), okajout, 160, 232);
  gtk_widget_set_size_request (okajout, 72, 34);

  label137 = gtk_label_new (_("<span color='black' size='large'>Votre ajout est r\303\251ussite.</span>"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed11), label137, 104, 112);
  gtk_widget_set_size_request (label137, 208, 33);
  gtk_label_set_use_markup (GTK_LABEL (label137), TRUE);

  image32 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_DND);
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed11), image32, 48, 112);
  gtk_widget_set_size_request (image32, 56, 37);

  g_signal_connect ((gpointer) okajout, "clicked",
                    G_CALLBACK (on_okajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutoui, ajoutoui, "ajoutoui");
  GLADE_HOOKUP_OBJECT (ajoutoui, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (ajoutoui, okajout, "okajout");
  GLADE_HOOKUP_OBJECT (ajoutoui, label137, "label137");
  GLADE_HOOKUP_OBJECT (ajoutoui, image32, "image32");

  return ajoutoui;
}

GtkWidget*
create_modoui (void)
{
  GtkWidget *modoui;
  GtkWidget *fixed12;
  GtkWidget *okmod;
  GtkWidget *label138;
  GtkWidget *modd;

  modoui = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (modoui, 400, 300);
  gtk_window_set_title (GTK_WINDOW (modoui), _("Alerte De Modification"));
  gtk_window_set_position (GTK_WINDOW (modoui), GTK_WIN_POS_CENTER);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (modoui), fixed12);

  okmod = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (okmod);
  gtk_fixed_put (GTK_FIXED (fixed12), okmod, 168, 240);
  gtk_widget_set_size_request (okmod, 66, 29);

  label138 = gtk_label_new (_("<span color='black' size='large'>Votre modification  est r\303\251ussite.</span>"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed12), label138, 80, 120);
  gtk_widget_set_size_request (label138, 272, 25);
  gtk_label_set_use_markup (GTK_LABEL (label138), TRUE);

  modd = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_DND);
  gtk_widget_show (modd);
  gtk_fixed_put (GTK_FIXED (fixed12), modd, 40, 112);
  gtk_widget_set_size_request (modd, 56, 29);

  g_signal_connect ((gpointer) okmod, "clicked",
                    G_CALLBACK (on_okmod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modoui, modoui, "modoui");
  GLADE_HOOKUP_OBJECT (modoui, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (modoui, okmod, "okmod");
  GLADE_HOOKUP_OBJECT (modoui, label138, "label138");
  GLADE_HOOKUP_OBJECT (modoui, modd, "modd");

  return modoui;
}

GtkWidget*
create_suppoui (void)
{
  GtkWidget *suppoui;
  GtkWidget *fixed13;
  GtkWidget *suppok;
  GtkWidget *image33;
  GtkWidget *label139;

  suppoui = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (suppoui, 400, 300);
  gtk_window_set_title (GTK_WINDOW (suppoui), _("window1"));
  gtk_window_set_position (GTK_WINDOW (suppoui), GTK_WIN_POS_CENTER);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (suppoui), fixed13);

  suppok = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (suppok);
  gtk_fixed_put (GTK_FIXED (fixed13), suppok, 168, 240);
  gtk_widget_set_size_request (suppok, 66, 29);

  image33 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_DND);
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed13), image33, 24, 112);
  gtk_widget_set_size_request (image33, 40, 37);

  label139 = gtk_label_new (_("<span color='black' size='large' >Votre suppression a \303\251t\303\251 effectu\303\251e\n                     avec success.</span>"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed13), label139, 64, 112);
  gtk_widget_set_size_request (label139, 288, 41);
  gtk_label_set_use_markup (GTK_LABEL (label139), TRUE);

  g_signal_connect ((gpointer) suppok, "clicked",
                    G_CALLBACK (on_suppok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppoui, suppoui, "suppoui");
  GLADE_HOOKUP_OBJECT (suppoui, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (suppoui, suppok, "suppok");
  GLADE_HOOKUP_OBJECT (suppoui, image33, "image33");
  GLADE_HOOKUP_OBJECT (suppoui, label139, "label139");

  return suppoui;
}

GtkWidget*
create_alerte (void)
{
  GtkWidget *alerte;
  GtkWidget *fixed14;
  GtkWidget *oui;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image35;
  GtkWidget *label142;
  GtkWidget *non;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image36;
  GtkWidget *label143;
  GtkWidget *image41;
  GtkWidget *label144;
  GtkWidget *lab;

  alerte = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (alerte, 400, 300);
  gtk_window_set_title (GTK_WINDOW (alerte), _("window2"));
  gtk_window_set_position (GTK_WINDOW (alerte), GTK_WIN_POS_CENTER);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (alerte), fixed14);

  oui = gtk_button_new ();
  gtk_widget_show (oui);
  gtk_fixed_put (GTK_FIXED (fixed14), oui, 88, 240);
  gtk_widget_set_size_request (oui, 66, 29);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (oui), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image35 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox32), image35, FALSE, FALSE, 0);

  label142 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label142);
  gtk_box_pack_start (GTK_BOX (hbox32), label142, FALSE, FALSE, 0);

  non = gtk_button_new ();
  gtk_widget_show (non);
  gtk_fixed_put (GTK_FIXED (fixed14), non, 248, 240);
  gtk_widget_set_size_request (non, 72, 29);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (non), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image36 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox33), image36, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox33), label143, FALSE, FALSE, 0);

  image41 = gtk_image_new_from_icon_name ("gtk-dialog-question", GTK_ICON_SIZE_DND);
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed14), image41, 24, 96);
  gtk_widget_set_size_request (image41, 32, 45);

  label144 = gtk_label_new (_("<span color='BLACK' >!!!Voulez Vous supprimer le troupeau \n                d'id: </span>"));
  gtk_widget_show (label144);
  gtk_fixed_put (GTK_FIXED (fixed14), label144, 64, 88);
  gtk_widget_set_size_request (label144, 280, 80);
  gtk_label_set_use_markup (GTK_LABEL (label144), TRUE);

  lab = gtk_label_new (_("label144"));
  gtk_widget_show (lab);
  gtk_fixed_put (GTK_FIXED (fixed14), lab, 136, 128);
  gtk_widget_set_size_request (lab, 128, 16);
  gtk_label_set_use_markup (GTK_LABEL (lab), TRUE);

  g_signal_connect ((gpointer) oui, "clicked",
                    G_CALLBACK (on_oui_clicked),
                    NULL);
  g_signal_connect ((gpointer) non, "clicked",
                    G_CALLBACK (on_non_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (alerte, alerte, "alerte");
  GLADE_HOOKUP_OBJECT (alerte, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (alerte, oui, "oui");
  GLADE_HOOKUP_OBJECT (alerte, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (alerte, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (alerte, image35, "image35");
  GLADE_HOOKUP_OBJECT (alerte, label142, "label142");
  GLADE_HOOKUP_OBJECT (alerte, non, "non");
  GLADE_HOOKUP_OBJECT (alerte, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (alerte, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (alerte, image36, "image36");
  GLADE_HOOKUP_OBJECT (alerte, label143, "label143");
  GLADE_HOOKUP_OBJECT (alerte, image41, "image41");
  GLADE_HOOKUP_OBJECT (alerte, label144, "label144");
  GLADE_HOOKUP_OBJECT (alerte, lab, "lab");

  return alerte;
}

GtkWidget*
create_suppfin (void)
{
  GtkWidget *suppfin;
  GtkWidget *fixed15;
  GtkWidget *okfin;
  GtkWidget *label146;
  GtkWidget *fin;
  GtkWidget *image37;

  suppfin = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (suppfin, 400, 300);
  gtk_window_set_title (GTK_WINDOW (suppfin), _("window1"));
  gtk_window_set_position (GTK_WINDOW (suppfin), GTK_WIN_POS_CENTER);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (suppfin), fixed15);

  okfin = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (okfin);
  gtk_fixed_put (GTK_FIXED (fixed15), okfin, 176, 240);
  gtk_widget_set_size_request (okfin, 66, 29);

  label146 = gtk_label_new (_("<span color='black' size='large'>suppression r\303\251ussite d'id: </span>"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed15), label146, 32, 96);
  gtk_widget_set_size_request (label146, 288, 57);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);

  fin = gtk_label_new (_("label147"));
  gtk_widget_show (fin);
  gtk_fixed_put (GTK_FIXED (fixed15), fin, 272, 112);
  gtk_widget_set_size_request (fin, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (fin), TRUE);

  image37 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_DND);
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed15), image37, 32, 104);
  gtk_widget_set_size_request (image37, 40, 37);

  g_signal_connect ((gpointer) okfin, "clicked",
                    G_CALLBACK (on_okfin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppfin, suppfin, "suppfin");
  GLADE_HOOKUP_OBJECT (suppfin, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (suppfin, okfin, "okfin");
  GLADE_HOOKUP_OBJECT (suppfin, label146, "label146");
  GLADE_HOOKUP_OBJECT (suppfin, fin, "fin");
  GLADE_HOOKUP_OBJECT (suppfin, image37, "image37");

  return suppfin;
}

GtkWidget*
create_typeinf (void)
{
  GtkWidget *typeinf;
  GtkWidget *fixed16;
  GtkWidget *oktype;
  GtkWidget *image38;
  GtkWidget *tpi;

  typeinf = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (typeinf, 400, 300);
  gtk_window_set_title (GTK_WINDOW (typeinf), _("window1"));
  gtk_window_set_position (GTK_WINDOW (typeinf), GTK_WIN_POS_CENTER);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (typeinf), fixed16);

  oktype = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (oktype);
  gtk_fixed_put (GTK_FIXED (fixed16), oktype, 168, 240);
  gtk_widget_set_size_request (oktype, 66, 29);

  image38 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_DND);
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed16), image38, 16, 104);
  gtk_widget_set_size_request (image38, 48, 45);

  tpi = gtk_label_new (_("label147"));
  gtk_widget_show (tpi);
  gtk_fixed_put (GTK_FIXED (fixed16), tpi, 16, 112);
  gtk_widget_set_size_request (tpi, 384, 33);

  g_signal_connect ((gpointer) oktype, "clicked",
                    G_CALLBACK (on_oktype_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (typeinf, typeinf, "typeinf");
  GLADE_HOOKUP_OBJECT (typeinf, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (typeinf, oktype, "oktype");
  GLADE_HOOKUP_OBJECT (typeinf, image38, "image38");
  GLADE_HOOKUP_OBJECT (typeinf, tpi, "tpi");

  return typeinf;
}

GtkWidget*
create_alerteopp (void)
{
  GtkWidget *alerteopp;
  GtkWidget *fixed17;
  GtkWidget *image42;
  GtkWidget *opplab;
  GtkWidget *oppmod;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image43;
  GtkWidget *label150;
  GtkWidget *oppsupp;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image44;
  GtkWidget *label151;
  GtkWidget *annuller;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image45;
  GtkWidget *label152;

  alerteopp = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (alerteopp, 400, 300);
  gtk_window_set_title (GTK_WINDOW (alerteopp), _("window1"));
  gtk_window_set_position (GTK_WINDOW (alerteopp), GTK_WIN_POS_CENTER);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (alerteopp), fixed17);

  image42 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_DND);
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed17), image42, 16, 104);
  gtk_widget_set_size_request (image42, 40, 37);

  opplab = gtk_label_new (_("label152"));
  gtk_widget_show (opplab);
  gtk_fixed_put (GTK_FIXED (fixed17), opplab, 56, 104);
  gtk_widget_set_size_request (opplab, 336, 41);

  oppmod = gtk_button_new ();
  gtk_widget_show (oppmod);
  gtk_fixed_put (GTK_FIXED (fixed17), oppmod, 240, 176);
  gtk_widget_set_size_request (oppmod, 104, 29);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (oppmod), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image43 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox35), image43, FALSE, FALSE, 0);

  label150 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (hbox35), label150, FALSE, FALSE, 0);

  oppsupp = gtk_button_new ();
  gtk_widget_show (oppsupp);
  gtk_fixed_put (GTK_FIXED (fixed17), oppsupp, 72, 176);
  gtk_widget_set_size_request (oppsupp, 104, 29);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (oppsupp), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image44 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox36), image44, FALSE, FALSE, 0);

  label151 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label151);
  gtk_box_pack_start (GTK_BOX (hbox36), label151, FALSE, FALSE, 0);

  annuller = gtk_button_new ();
  gtk_widget_show (annuller);
  gtk_fixed_put (GTK_FIXED (fixed17), annuller, 152, 248);
  gtk_widget_set_size_request (annuller, 104, 29);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (annuller), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image45 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox37), image45, FALSE, FALSE, 0);

  label152 = gtk_label_new_with_mnemonic (_("Anuller"));
  gtk_widget_show (label152);
  gtk_box_pack_start (GTK_BOX (hbox37), label152, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) oppmod, "clicked",
                    G_CALLBACK (on_oppmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) oppsupp, "clicked",
                    G_CALLBACK (on_oppsupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuller, "clicked",
                    G_CALLBACK (on_annuller_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (alerteopp, alerteopp, "alerteopp");
  GLADE_HOOKUP_OBJECT (alerteopp, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (alerteopp, image42, "image42");
  GLADE_HOOKUP_OBJECT (alerteopp, opplab, "opplab");
  GLADE_HOOKUP_OBJECT (alerteopp, oppmod, "oppmod");
  GLADE_HOOKUP_OBJECT (alerteopp, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (alerteopp, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (alerteopp, image43, "image43");
  GLADE_HOOKUP_OBJECT (alerteopp, label150, "label150");
  GLADE_HOOKUP_OBJECT (alerteopp, oppsupp, "oppsupp");
  GLADE_HOOKUP_OBJECT (alerteopp, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (alerteopp, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (alerteopp, image44, "image44");
  GLADE_HOOKUP_OBJECT (alerteopp, label151, "label151");
  GLADE_HOOKUP_OBJECT (alerteopp, annuller, "annuller");
  GLADE_HOOKUP_OBJECT (alerteopp, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (alerteopp, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (alerteopp, image45, "image45");
  GLADE_HOOKUP_OBJECT (alerteopp, label152, "label152");

  return alerteopp;
}

