/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowtroupeaux (void);
GtkWidget* create_affichagetroupeaux (void);
GtkWidget* create_windowsuppmod (void);
GtkWidget* create_idtroupeaumodifier (void);
GtkWidget* create_modifiertroupeau (void);
GtkWidget* create_typedetroupeaux (void);
GtkWidget* create_ajoutoui (void);
GtkWidget* create_modoui (void);
GtkWidget* create_suppoui (void);
GtkWidget* create_alerte (void);
GtkWidget* create_suppfin (void);
GtkWidget* create_typeinf (void);
GtkWidget* create_alerteopp (void);
