/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestioncapteur (void);
GtkWidget* create_addCapteur (void);
GtkWidget* create_DelCapteur (void);
GtkWidget* create_editCapteur (void);
GtkWidget* create_bestouvrier (void);
GtkWidget* create_capteurdef (void);
