/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestioncapteur;
  GtkWidget *addCapteur;
  GtkWidget *DelCapteur;
  GtkWidget *editCapteur;
  GtkWidget *Topouvrier;
  GtkWidget *bestouvrier;
GtkWidget*capteurdef;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gestioncapteur = create_gestioncapteur ();
  gtk_widget_show (gestioncapteur);
  /*addCapteur = create_addCapteur ();
  gtk_widget_show (addCapteur);
  DelCapteur = create_DelCapteur ();
  gtk_widget_show (DelCapteur);
  editCapteur = create_editCapteur ();
  gtk_widget_show (editCapteur);
  Topouvrier = create_Topouvrier ();
  gtk_widget_show (Topouvrier);
  bestouvrier = create_bestouvrier ();
  gtk_widget_show (bestouvrier);
	capteurdef=create_capteurdef();
gtk_widget_show(capteurdef);*/

  gtk_main ();
  return 0;
}

